/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or
// formatter to prevent it from being checked or modified.
// It will be regenerated by the TanStack Router plugin on `dev`/`build`.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as OtpRouteImport } from "./routes/otp";
import { Route as AppRouteImport } from "./routes/_app";
import { Route as AppHuntingMedicalIndexRouteImport } from "./routes/_app/hunting-medical/index";
import { Route as AppHuntingMedicalNewRouteImport } from "./routes/_app/hunting-medical/new";
import { Route as AppHuntingMedicalIdRouteImport } from "./routes/_app/hunting-medical/$id";
import { Route as AppHuntingMedicalIdEditRouteImport } from "./routes/_app/hunting-medical/$id.edit";
import { Route as AppHuntingMedicalIdAuditRouteImport } from "./routes/_app/hunting-medical/$id.audit";
import { Route as AppHuntingMedicalIdPrintRouteImport } from "./routes/_app/hunting-medical/$id.print";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
});

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
});

const OtpRoute = OtpRouteImport.update({
  id: "/otp",
  path: "/otp",
  getParentRoute: () => rootRouteImport,
});

const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
});

const AppHuntingMedicalIndexRoute = AppHuntingMedicalIndexRouteImport.update({
  id: "/hunting-medical/",
  path: "/hunting-medical/",
  getParentRoute: () => AppRoute,
});

const AppHuntingMedicalNewRoute = AppHuntingMedicalNewRouteImport.update({
  id: "/hunting-medical/new",
  path: "/hunting-medical/new",
  getParentRoute: () => AppRoute,
});

const AppHuntingMedicalIdRoute = AppHuntingMedicalIdRouteImport.update({
  id: "/hunting-medical/$id",
  path: "/hunting-medical/$id",
  getParentRoute: () => AppRoute,
});

const AppHuntingMedicalIdEditRoute = AppHuntingMedicalIdEditRouteImport.update({
  id: "/hunting-medical/$id/edit",
  path: "/hunting-medical/$id/edit",
  getParentRoute: () => AppRoute,
});

const AppHuntingMedicalIdAuditRoute = AppHuntingMedicalIdAuditRouteImport.update(
  {
    id: "/hunting-medical/$id/audit",
    path: "/hunting-medical/$id/audit",
    getParentRoute: () => AppRoute,
  },
);

const AppHuntingMedicalIdPrintRoute = AppHuntingMedicalIdPrintRouteImport.update(
  {
    id: "/hunting-medical/$id/print",
    path: "/hunting-medical/$id/print",
    getParentRoute: () => AppRoute,
  },
);

const AppRouteChildren = {
  AppHuntingMedicalIndexRoute,
  AppHuntingMedicalNewRoute,
  AppHuntingMedicalIdRoute,
  AppHuntingMedicalIdEditRoute,
  AppHuntingMedicalIdAuditRoute,
  AppHuntingMedicalIdPrintRoute,
};

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren);

const rootRouteChildren = {
  IndexRoute,
  LoginRoute,
  OtpRoute,
  AppRoute: AppRouteWithChildren,
};

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes();
